### ISSUE TITLE
GitHub release?

### ISSUE THREAD

**Issue by jitpack** [jordw/heftydb#3]
Would be great to have some sort of GitHub release so that its easier to grab the HeftyDb lib

**Comment by jordw** [comment]
Sure, I'll do that.

**Comment by jordw** [comment]
Done, Thanks

**Comment by jitpack-io** [comment]
Cool! Btw, with a GitHub release it becomes available on JitPack.io:
https://jitpack.io/#jordw/heftydb/v0.9

as a maven artifact.
